name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Necessary to get all tags and history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Ensure this matches your project's Node.js version

      # - name: Semantic Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # - name: Get the latest tag name
      #   id: get-latest-tag
      #   run: echo "tag=$(git describe --tags $(git rev-list --tags --max-count=1))" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/turkibash/nodeapp:v1.2

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
        run: echo "${KUBECONFIG_CONTENTS}" | base64 -d > ${{ github.workspace }}/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig ${{ github.workspace }}/kubeconfig apply -f kubernetes/deployment.yaml
          kubectl --kubeconfig ${{ github.workspace }}/kubeconfig apply -f kubernetes/service.yaml
