name: Deploy to Kubernetes Cluster

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/turkibash/nodeapp:v1

      - name: Set up Kubeconfig
        env:
          KUBECONFIG_CONTENTS: ${{ secrets.KUBECONFIG }}
        run: echo "${KUBECONFIG_CONTENTS}" | base64 -d > ${{ github.workspace }}/kubeconfig

      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig ${{ github.workspace }}/kubeconfig apply -f kubernetes/deployment.yaml
          kubectl --kubeconfig ${{ github.workspace }}/kubeconfig apply -f kubernetes/service.yaml
