name: Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important: This allows Semantic Release to analyze the commit history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Use the Node.js version compatible with your project

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub token for publishing the release
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }} # Uncomment if you publish to npm
