name: Release

on:
  push:
    branches:
      - main

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Important: This allows Semantic Release to analyze the commit history

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Use the Node.js version compatible with your project

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
